added button to report bug in github
GeneralMagicio/pairwise-RPGF4 pull request #98
Opened 2024-06-21 17:35 UTC by lovelgeorge99

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/36924734/15fa2ec9-d98b-462a-af36-16d1ed07895f)

2024-06-25 08:42 UTC, MoeNick commented on src/app/categories/page.tsx
> +				<a target="_blank" href='https://github.com/GeneralMagicio/pairwise-RPGF4/issues'>
<a target="_blank" href='https://github.com/GeneralMagicio/pairwise-RPGF4/issues/new?assignees=MoeNick&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D+'>

2024-06-25 08:44 UTC, MoeNick requested changes
Please use the report a bug template URL.  @lovelgeorge99

2024-06-25 08:44 UTC, MoeNick commented on src/app/categories/page.tsx
> +				<a target="_blank" href='https://github.com/GeneralMagicio/pairwise-RPGF4/issues'>
https://github.com/GeneralMagicio/pairwise-RPGF4/issues/new?assignees=MoeNick&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D+

2024-06-27 07:40 UTC, mmahdigh approved these changes

2024-06-27 07:41 UTC, merged